### ISSUE TITLE
Fatal Error during blockchain activation

### ISSUE THREAD

**Issue by BardoBravo** [sandoche/Proof-of-Stake-Cryptocurrency-generator#14]
When performing the step 2 (Create your own Cryptocurrency), the error **SEVERE: Error in block generation thread** is raised in the console.

Also, the account balance is showed as -999,999,999 and not connected, as displayed in this [shared link](https://www.dropbox.com/s/11d21ew54slsy8d/Error_block_generator.png?dl=0)

Any idea on how to solve it?

Regards

**Comment by sandoche** [comment]
Hello I think, there was a missing point in step 1:
"Edit the genesisParameters.json file to define the timestamp of the genesis block for your new blockchain (epochBeginning), and the public key of the genesis account (genesisPublicKey)."

Be sure that the public key of the genesis account is not the same as the public keys you put in genesisAccounts.json

I invite you to do again step 1, maybe follow the video tutorial of NXT: https://www.youtube.com/watch?v=6Wg3uv07GU4

**Comment by BardoBravo** [comment]
Hello,
I have followed the step 1 and created a new account, assigning its public key to 'genesisPublicKey' of genesisParameters.json file.

Any other suggestion?

**Comment by BardoBravo** [comment]
UPDATE: After machine restart, system now informs **FINE: forger #### deadline 0 hit 0 started**

**Comment by BardoBravo** [comment]
Yes :(

**Comment by sandoche** [comment]
Maybe you should contact the NXT Support in the NXT Slack.
Also, check this video: https://www.youtube.com/watch?v=6Wg3uv07GU4 to be sure you didn't do anything wrong in the Step 1.

**Comment by BardoBravo** [comment]
Hi,
I have done it all again and now I have the following issue and trying to run the crypto folder (Build your Crypto steps):
"
java.lang.RuntimeException: Errors running startup tasks:org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: "BLOCK_ID_IDX ON PUBLIC.BLOCK(ID) VALUES ( /* 4 */ -5953303402691474650 )"; SQL statement:INSERT INTO block (id, version, timestamp, previous_block_id, total_amount, total_fee, payload_length, previous_block_hash, next_block_id, cumulative_difficulty, base_target, height, generation_signature, block_signature, payload_hash, generator_id)  VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23505-196]
"
It seems the parameter values are being sent as '?'.

Any suggestion?

**Comment by sandoche** [comment]
Yes, go to your crypto's folder and delete the nxt_db folder

**Comment by BardoBravo** [comment]
Hi,
After deleting the folder, another issue is raised:
"
nxt.BlockchainProcessorImpl.addGenesisBlock(BlockchainProcessorImpl.java:1286)  nxt.BlockchainProcessorImpl.lambda$new$5(BlockchainProcessorImpl.java:971)  nxt.util.ThreadPool.lambda$runAll$1(ThreadPool.java:126)Exception in thread "Thread-2" java.lang.NullPointerException	at nxt.Genesis.apply(Genesis.java:92)	at nxt.BlockchainProcessorImpl.addGenesisBlock(BlockchainProcessorImpl.java:1275)	at nxt.BlockchainProcessorImpl.lambda$new$5(BlockchainProcessorImpl.java:971)	at nxt.util.ThreadPool.lambda$runAll$1(ThreadPool.java:126)	at java.base/java.lang.Thread.run(Thread.java:844)

2018-05-18 13:14:22 SEVERE: Errors running startup tasks:nulljava.lang.RuntimeException: Errors running startup tasks:null	at nxt.util.ThreadPool.runAll(ThreadPool.java:144)	at nxt.util.ThreadPool.start(ThreadPool.java:74)	at nxt.Nxt$Init.<clinit>(Nxt.java:395)	at nxt.Nxt.init(Nxt.java:327)	at nxt.Nxt.main(Nxt.java:314)
"

If I execute run.sh again, the same error with parameters as '?' is displayed.

**Comment by sandoche** [comment]
Have you updated the file genesisAccounts.json in the folder conf/data of your cryptocurrency, after your regenerated it?

**Comment by setarehAf** [comment]
hello,
In step 1 cause I work on windows, I've use win-compile.sh and then run.bat. also I have java JRE on my system I face this error when use run.bat 
"Java version in "HKLM\SOFTWARE\JavaSoft\Java Runtime Environment" is "" and in "HKLM\SOFTWARE\Wow6432Node\JavaSoft\Java Run Time environment" is "" java not found,please install java JRE". 
how can I solve this?

**Comment by sandoche** [comment]
Yes it's supposed to be connected. Is your total in genesisAccounts.json equals to 1 billion ?

**Comment by Casper0513** [comment]
I have set mine to 1 billion but I am getting this error
 java.lang.RuntimeException: Errors running startup tasks:
Total balance 299999999999957354 exceeds maximum allowed 100000000000000000

**Comment by sandoche** [comment]
This means your genesis block file is not well configured the total sum should equal 100000000000000000
