### ISSUE TITLE
severe error

### ISSUE THREAD

**Issue by earthirian** [sandoche/Proof-of-Stake-Cryptocurrency-generator#19]
Hi,

I generated currency successfully. When uploaded in production server to get it live i am getting following error after issuing command curl -d requestType=startForging -d secretPhrase="<passphrase>" http://localhost:<port>/nxt

error i am getting:

	at nxt.Generator.setLastBlock(Generator.java:323)
	at nxt.Generator.access$400(Generator.java:40)
	at nxt.Generator$1.run(Generator.java:79)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-09-09 11:30:55 SEVERE: Error in block generation thread
java.lang.NullPointerException
	at nxt.Generator.setLastBlock(Generator.java:323)
	at nxt.Generator.access$400(Generator.java:40)
	at nxt.Generator$1.run(Generator.java:79)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-09-09 11:30:55 SEVERE: Error in block generation thread
java.lang.NullPointerException
	at nxt.Generator.setLastBlock(Generator.java:323)
	at nxt.Generator.access$400(Generator.java:40)
	at nxt.Generator$1.run(Generator.java:79)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-09-09 11:30:56 SEVERE: Error in block generation thread
java.lang.NullPointerException

where am i going wrong?

**Comment by earthirian** [comment]
I am sorry .. it's forging and generating blocks... thanks.

Further if I have any issue i will let you know.

Thanks
