### ISSUE TITLE
run.bat problem

### ISSUE THREAD

**Issue by ballgamer56** [sandoche/Proof-of-Stake-Cryptocurrency-generator#20]
I run into a problem (as shown in the picture and the log file) Can you help me with it?
[nxt.log](https://github.com/sandoche/Proof-of-Stake-Cryptocurrency-generator/files/2407872/nxt.log)
thanks

P.s.
I didn't use sh ./run.bat because it doesn't work so I just normally open that file
![untitled](https://user-images.githubusercontent.com/30421594/45918397-a82f6500-beb0-11e8-9850-66e77592f592.png)

**Comment by sandoche** [comment]
Hi sorry for the delay. Can you try with git bash on windows?

**Comment by ballgamer56** [comment]
I've try it. this is what happen :
$ sh ./run.bat
./run.bat: line 1: @echo: command not found
./run.bat: line 2: syntax error near unexpected token `('
./run.bat: line 2: `    if exist jre ( '

P.s. I'm glad that you didn't abandoned this project :D

**Comment by sandoche** [comment]
Actually you don't have to run it with sh. You can just open it since it's a bat file.

**Comment by ballgamer56** [comment]
I run it and the problem is the top picture appear. idk why

**Comment by sandoche** [comment]
Did you run `sh ./win-compile.sh` before?

**Comment by ballgamer56** [comment]
yes I already run it and after that I open the run.bat file and it came up with the message above

**Comment by ballgamer56** [comment]
I guess maybe I did something wrong in the early process. I'll start over and see if the problem is still there

**Comment by ballgamer56** [comment]
and.... nope same issue

**Comment by sandoche** [comment]
Can you copy paste the logs?

**Comment by ballgamer56** [comment]
sorry for a very late reply
here it is : 
2561-10-17 12:49:08 INFO: nxt.enableStackTraces = "true"
2561-10-17 12:49:08 INFO: nxt.enableLogTraceback = "false"
2561-10-17 12:49:08 INFO: logging enabled
2561-10-17 12:49:08 INFO: socksProxyHost not defined
2561-10-17 12:49:08 INFO: socksProxyPort not defined
2561-10-17 12:49:08 FINE: java.version = 1.8.0_181
2561-10-17 12:49:08 FINE: java.vm.version = 25.181-b13
2561-10-17 12:49:08 FINE: java.vm.name = Java HotSpot(TM) Client VM
2561-10-17 12:49:08 FINE: java.vendor = Oracle Corporation
2561-10-17 12:49:08 FINE: java.vm.vendor = Oracle Corporation
2561-10-17 12:49:08 FINE: java.home = C:\Program Files (x86)\Java\jre1.8.0_181
2561-10-17 12:49:08 FINE: java.library.path = C:\Program Files (x86)\Java\jre1.8.0_181\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\IVI Foundation\VISA\WinNT\Bin;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\Program Files (x86)\Yarn\bin\;C:\Program Files\Git\cmd;C:\Users\Asus\AppData\Local\Microsoft\WindowsApps;C:\Users\Asus\AppData\Roaming\npm;C:\Users\Asus\AppData\Local\Yarn\bin;C:\Program Files (x86)\Java\;C:\Users\Asus\AppData\Local\Microsoft\WindowsApps;C:\Users\Asus\AppData\Roaming\npm;C:\Users\Asus\AppData\Local\Yarn\bin;C:\Program Files (x86)\Java\jdk1.8.0_171\bin;;C:\Program Files\Docker Toolbox;.
2561-10-17 12:49:08 FINE: java.class.path = classes;lib\bcprov-jdk15on-159.jar;lib\core-3.3.0.jar;lib\h2-1.4.196.jar;lib\javase-3.3.0.jar;lib\javax.servlet-api-3.1.0.jar;lib\jetty-client-9.3.22.v20171030.jar;lib\jetty-continuation-9.3.22.v20171030.jar;lib\jetty-http-9.3.22.v20171030.jar;lib\jetty-io-9.3.22.v20171030.jar;lib\jetty-proxy-9.3.22.v20171030.jar;lib\jetty-security-9.3.22.v20171030.jar;lib\jetty-server-9.3.22.v20171030.jar;lib\jetty-servlet-9.3.22.v20171030.jar;lib\jetty-servlets-9.3.22.v20171030.jar;lib\jetty-util-9.3.22.v20171030.jar;lib\json-simple-1.1.1.jar;lib\lucene-analyzers-common-5.5.5.jar;lib\lucene-backward-codecs-5.5.5.jar;lib\lucene-core-5.5.5.jar;lib\lucene-queries-5.5.5.jar;lib\lucene-queryparser-5.5.5.jar;lib\slf4j-api-1.7.22.jar;lib\slf4j-jdk14-1.7.22.jar;lib\tika-core-1.13.jar;lib\tika-parsers-1.13.jar;lib\websocket-api-9.3.22.v20171030.jar;lib\websocket-client-9.3.22.v20171030.jar;lib\websocket-common-9.3.22.v20171030.jar;lib\websocket-server-9.3.22.v20171030.jar;lib\websocket-servlet-9.3.22.v20171030.jar;lib\weupnp-0.1.4.jar;conf;addons\classes;addons\lib\*
2561-10-17 12:49:08 FINE: os.arch = x86
2561-10-17 12:49:08 FINE: sun.arch.data.model = 32
2561-10-17 12:49:08 FINE: os.name = Windows 10
2561-10-17 12:49:08 FINE: file.encoding = MS874
2561-10-17 12:49:08 FINE: java.security.policy = null
2561-10-17 12:49:08 FINE: java.security.manager = null
2561-10-17 12:49:08 FINE: nxt.runtime.mode = desktop
2561-10-17 12:49:08 FINE: nxt.runtime.dirProvider = null
2561-10-17 12:49:08 FINE: availableProcessors = 4
2561-10-17 12:49:08 FINE: maxMemory = 259522560
2561-10-17 12:49:08 FINE: processId = 4216
2561-10-17 12:49:09 INFO: nxt.isTestnet = "false"
2561-10-17 12:49:09 INFO: nxt.isOffline = "false"
2561-10-17 12:49:09 INFO: nxt.isLightClient = "false"
2561-10-17 12:49:09 INFO: nxt.customLoginWarning not defined
2561-10-17 12:49:09 INFO: nxt.maxNumberOfTransactions not defined or not numeric, using default value 255
2561-10-17 12:49:09 INFO: nxt.maxRollback = "800"
2561-10-17 12:49:09 INFO: nxt.forgingDelay = "20"
2561-10-17 12:49:09 INFO: nxt.forgingSpeedup = "3"
2561-10-17 12:49:09 INFO: nxt.batchCommitSize = "100"
2561-10-17 12:49:09 INFO: nxt.maxPrunableLifetime = "7776000"
2561-10-17 12:49:09 INFO: nxt.launchDesktopApplication = "true"
2561-10-17 12:49:09 INFO: nxt.includeExpiredPrunable = "true"
2561-10-17 12:49:09 INFO: nxt.correctInvalidFees = "false"
2561-10-17 12:49:09 INFO: nxt.statementLogThreshold = "10000"
2561-10-17 12:49:09 INFO: nxt.transactionLogThreshold = "15000"
2561-10-17 12:49:09 INFO: nxt.transactionLogInterval = "15"
2561-10-17 12:49:09 INFO: nxt.dbCacheKB = "0"
2561-10-17 12:49:09 INFO: nxt.dbUrl not defined
2561-10-17 12:49:09 INFO: nxt.dbType = "h2"
2561-10-17 12:49:09 INFO: nxt.dbDir = "./nxt_db/nxt"
2561-10-17 12:49:09 INFO: nxt.dbParams = "DB_CLOSE_ON_EXIT=FALSE;MVCC=TRUE;MV_STORE=FALSE"
2561-10-17 12:49:09 INFO: nxt.dbUsername = "sa"
2561-10-17 12:49:09 INFO: nxt.dbPassword = "{not logged}"
2561-10-17 12:49:09 INFO: nxt.maxDbConnections = "30"
2561-10-17 12:49:09 INFO: nxt.dbLoginTimeout = "70"
2561-10-17 12:49:09 INFO: nxt.dbDefaultLockTimeout = "60"
2561-10-17 12:49:09 INFO: nxt.dbMaxMemoryRows = "1000000"
2561-10-17 12:49:09 FINE: Database jdbc url set to jdbc:h2:C:\Users\Asus\AppData\Roaming\VISUTCRYPTOCOIN\.\nxt_db\nxt;DB_CLOSE_ON_EXIT=FALSE;MVCC=TRUE;MV_STORE=FALSE;CACHE_SIZE=60416 username sa
2561-10-17 12:49:09 INFO: nxt.useStrongSecureRandom = "false"
2561-10-17 12:49:09 FINE: Database connection pool current size: 1
2561-10-17 12:49:09 INFO: Database update may take a while if needed, current db version 237...
2561-10-17 12:49:09 INFO: nxt.enableTransactionRebroadcasting = "true"
2561-10-17 12:49:09 INFO: nxt.testUnconfirmedTransactions not defined, using default false
2561-10-17 12:49:09 INFO: nxt.maxUnconfirmedTransactions = "2000"
2561-10-17 12:49:09 INFO: nxt.trimDerivedTables = "true"
2561-10-17 12:49:09 INFO: nxt.numberOfForkConfirmations = "0"
2561-10-17 12:49:09 INFO: nxt.simulateEndlessDownload not defined, using default false
2561-10-17 12:49:09 INFO: nxt.trimFrequency = "1000"
2561-10-17 12:49:09 INFO: nxt.disableGetMoreBlocksThread not defined, using default false
2561-10-17 12:49:10 INFO: nxt.disableProcessTransactionsThread not defined, using default false
2561-10-17 12:49:10 INFO: nxt.disableRebroadcastTransactionsThread not defined, using default false
2561-10-17 12:49:10 INFO: nxt.disableRemoveUnconfirmedTransactionsThread not defined, using default false
2561-10-17 12:49:10 INFO: nxt.disableProcessWaitingTransactionsThread not defined, using default false
2561-10-17 12:49:10 INFO: nxt.enablePublicKeyCache = "true"
2561-10-17 12:49:10 INFO: nxt.ledgerTrimKeep = "30000"
2561-10-17 12:49:10 INFO: nxt.ledgerAccounts = "*"
2561-10-17 12:49:10 INFO: Account ledger is tracking all accounts
2561-10-17 12:49:10 INFO: nxt.ledgerLogUnconfirmed = "2"
2561-10-17 12:49:10 INFO: nxt.processPolls = "true"
2561-10-17 12:49:10 INFO: nxt.deleteFinishedShufflings = "false"
2561-10-17 12:49:10 INFO: nxt.maxPeerRequestSize not defined or not numeric, using default value 1048576
2561-10-17 12:49:10 INFO: nxt.maxPeerResponseSize not defined or not numeric, using default value 1048576
2561-10-17 12:49:10 INFO: nxt.maxPeerMessageSize not defined or not numeric, using default value 10485760
2561-10-17 12:49:10 INFO: nxt.hideErrorDetails = "false"
2561-10-17 12:49:10 INFO: nxt.myPlatform not defined
2561-10-17 12:49:10 INFO: nxt.myAddress not defined
2561-10-17 12:49:10 INFO: nxt.peerServerPort = "6000"
2561-10-17 12:49:10 INFO: nxt.shareMyAddress = "true"
2561-10-17 12:49:10 INFO: nxt.enablePeerUPnP = "true"
2561-10-17 12:49:10 INFO: nxt.myHallmark not defined
2561-10-17 12:49:10 INFO: nxt.adminPassword not defined
2561-10-17 12:49:10 INFO: nxt.maxAPIRecords = "100"
2561-10-17 12:49:10 INFO: nxt.enableAPIUPnP = "false"
2561-10-17 12:49:10 INFO: nxt.apiServerIdleTimeout = "30000"
2561-10-17 12:49:10 INFO: nxt.apiServerCORS = "true"
2561-10-17 12:49:10 INFO: nxt.forwardedForHeader not defined
2561-10-17 12:49:10 INFO: nxt.disabledAPIs not defined
2561-10-17 12:49:10 INFO: nxt.disabledAPITags not defined
2561-10-17 12:49:10 INFO: nxt.allowedBotHosts = "127.0.0.1; localhost; [0:0:0:0:0:0:0:1];"
2561-10-17 12:49:10 INFO: nxt.enableAPIServer = "true"
2561-10-17 12:49:10 INFO: nxt.apiServerPort = "8000"
2561-10-17 12:49:10 INFO: nxt.apiServerSSLPort = "7876"
2561-10-17 12:49:10 INFO: nxt.apiServerHost = "127.0.0.1"
2561-10-17 12:49:10 INFO: nxt.disableAdminPassword = "false"
2561-10-17 12:49:10 INFO: nxt.apiSSL = "false"
2561-10-17 12:49:10 INFO: API server using HTTP port 8000
2561-10-17 12:49:10 INFO: nxt.apiResourceBase = "./html/www"
2561-10-17 12:49:10 INFO: nxt.apiWelcomeFile = "index.html"
2561-10-17 12:49:10 INFO: nxt.javadocResourceBase = "./html/doc"
2561-10-17 12:49:10 INFO: nxt.maxUploadFileSize not defined or not numeric, using default value 0
2561-10-17 12:49:10 INFO: nxt.maxUploadFileSize not defined or not numeric, using default value 0
2561-10-17 12:49:10 INFO: nxt.enableAPIServerGZIPFilter not defined, using default false
2561-10-17 12:49:10 INFO: nxt.apiFrameOptionsSameOrigin = "true"
2561-10-17 12:49:10 FINE: My peer info:
{"application":"VisutCryptoCoin","services":"0","version":"1.11.13","platform":"Windows 10 x86","shareAddress":true}
2561-10-17 12:49:10 INFO: nxt.defaultPeers not defined
2561-10-17 12:49:10 INFO: nxt.wellKnownPeers not defined
2561-10-17 12:49:10 INFO: nxt.knownBlacklistedPeers not defined
2561-10-17 12:49:10 INFO: nxt.maxNumberOfInboundConnections = "2000"
2561-10-17 12:49:10 INFO: nxt.maxNumberOfOutboundConnections = "50"
2561-10-17 12:49:10 INFO: nxt.maxNumberOfConnectedPublicPeers = "20"
2561-10-17 12:49:10 INFO: nxt.maxNumberOfKnownPeers = "2000"
2561-10-17 12:49:10 INFO: nxt.minNumberOfKnownPeers = "1000"
2561-10-17 12:49:10 INFO: nxt.connectTimeout = "10000"
2561-10-17 12:49:10 INFO: nxt.readTimeout = "20000"
2561-10-17 12:49:10 INFO: nxt.enableHallmarkProtection = "true"
2561-10-17 12:49:10 INFO: nxt.pushThreshold = "0"
2561-10-17 12:49:10 INFO: nxt.pullThreshold = "0"
2561-10-17 12:49:10 INFO: nxt.useWebSockets = "true"
2561-10-17 12:49:10 INFO: nxt.webSocketIdleTimeout = "900000"
2561-10-17 12:49:10 INFO: nxt.enablePeerServerGZIPFilter = "true"
2561-10-17 12:49:10 INFO: nxt.blacklistingPeriod = "600000"
2561-10-17 12:49:10 INFO: nxt.communicationLoggingMask = "0"
2561-10-17 12:49:10 INFO: nxt.sendToPeersLimit = "10"
2561-10-17 12:49:10 INFO: nxt.usePeersDb = "true"
2561-10-17 12:49:10 INFO: nxt.savePeers = "true"
2561-10-17 12:49:10 INFO: nxt.getMorePeers = "true"
2561-10-17 12:49:10 INFO: nxt.cjdnsOnly = "false"
2561-10-17 12:49:10 INFO: nxt.ignorePeerAnnouncedAddress = "false"
2561-10-17 12:49:10 INFO: nxt.disablePeerConnectingThread not defined, using default false
2561-10-17 12:49:10 INFO: nxt.disablePeerUnBlacklistingThread not defined, using default false
2561-10-17 12:49:10 INFO: nxt.disableGetMorePeersThread not defined, using default false
2561-10-17 12:49:10 INFO: nxt.peerServerHost = "0.0.0.0"
2561-10-17 12:49:10 INFO: nxt.peerServerIdleTimeout = "30000"
2561-10-17 12:49:10 INFO: nxt.enablePeerServerDoSFilter = "true"
2561-10-17 12:49:10 INFO: nxt.peerServerDoSFilter.maxRequestsPerSec = "30"
2561-10-17 12:49:10 INFO: nxt.peerServerDoSFilter.delayMs = "1000"
2561-10-17 12:49:10 INFO: nxt.peerServerDoSFilter.maxRequestMs = "300000"
2561-10-17 12:49:10 INFO: nxt.enableAPIProxy = "true"
2561-10-17 12:49:10 INFO: nxt.apiProxyBlacklistingPeriod = "1800000"
2561-10-17 12:49:10 INFO: nxt.forceAPIProxyServerURL not defined
2561-10-17 12:49:10 INFO: nxt.disableAPIProxyPeersUpdateThread not defined, using default false
2561-10-17 12:49:10 INFO: nxt.maxNumberOfForgers = "100"
2561-10-17 12:49:10 INFO: nxt.enableFakeForging not defined, using default false
2561-10-17 12:49:10 INFO: nxt.disableGenerateBlocksThread not defined, using default false
2561-10-17 12:49:10 INFO: nxt.addOns not defined
2561-10-17 12:49:10 INFO: nxt.debugTraceQuote = """
2561-10-17 12:49:10 INFO: nxt.debugTraceSeparator = "	"
2561-10-17 12:49:10 INFO: nxt.debugLogUnconfirmed = "false"
2561-10-17 12:49:10 INFO: nxt.debugTraceAccounts not defined
2561-10-17 12:49:10 INFO: nxt.debugTraceLog = "nxt-trace.csv"
2561-10-17 12:49:10 FINE: Running 2 tasks...
2561-10-17 12:49:10 FINE: Loading known peers from the database...
2561-10-17 12:49:10 INFO: Genesis block not in database, starting from scratch
2561-10-17 12:49:10 FINE: Database connection pool current size: 2
2561-10-17 12:49:10 FINE: Loading public keys
2561-10-17 12:49:10 FINE: Average database transaction time is 0.019 seconds
2561-10-17 12:49:10 SEVERE: Errors running startup tasks:
null

java.lang.RuntimeException: Errors running startup tasks:
null

	at nxt.util.ThreadPool.runAll(ThreadPool.java:144)
	at nxt.util.ThreadPool.start(ThreadPool.java:74)
	at nxt.Nxt$Init.<clinit>(Nxt.java:395)
	at nxt.Nxt.init(Nxt.java:327)
	at nxt.Nxt.main(Nxt.java:314)
2561-10-17 12:49:13 INFO: Shutting down...
2561-10-17 12:49:13 INFO: nxt.maxNumberOfMonitors = "100"
2561-10-17 12:49:13 INFO: shutting down networkService
2561-10-17 12:49:13 INFO: shutting down sendingService
2561-10-17 12:49:13 INFO: shutting down peersService
2561-10-17 12:49:13 INFO: Database shutdown completed
2561-10-17 12:49:13 INFO: VisutCryptoCoin server 1.11.13 stopped.

**Comment by sandoche** [comment]
Maybe you should delete the `nxt_db` folder and run it again.

**Comment by ballgamer56** [comment]
You mean delete the (my cryptocurrency's name)/classes/nxt/db right? (because I can't find the file or folder named "nxt_db") If that's the case It seem to help. I'm no longer get the error message, waiting for it to loading database (the mini icon said it loading) hopefully it doesn't stuck. [sorry for not reply you faster. I just get back to work on this project]

**Comment by ballgamer56** [comment]
and the cmd stuck on this 👍 
Initializing VisutCryptoCoin server version 1.11.13
Command line arguments
-Dnxt.runtime.mode=desktop
isHeadless=false
Runtime mode nxt.env.DesktopMode
User home folder C:\Users\Asus\AppData\Roaming\VISUTCRYPTOCOIN
Loading nxt-default.properties from classpath
Loading nxt-installer.properties from dir C:\Users\Asus\AppData\Roaming\VISUTCRYPTOCOIN\conf
Loading nxt.properties from dir C:\Users\Asus\AppData\Roaming\VISUTCRYPTOCOIN\conf
Loading logging-default.properties from classpath
Loading logging.properties from dir C:\Users\Asus\AppData\Roaming\VISUTCRYPTOCOIN\conf
Logs dir C:\Users\Asus\AppData\Roaming\VISUTCRYPTOCOIN\logs
2561-12-30 18:48:29 INFO: nxt.enableStackTraces = "true"
2561-12-30 18:48:30 INFO: nxt.enableLogTraceback = "false"
2561-12-30 18:48:30 INFO: logging enabled
2561-12-30 18:48:30 INFO: socksProxyHost not defined
2561-12-30 18:48:30 INFO: socksProxyPort not defined
2561-12-30 18:48:30 FINE: java.version = 1.8.0_191
2561-12-30 18:48:30 FINE: java.vm.version = 25.191-b12
2561-12-30 18:48:30 FINE: java.vm.name = Java HotSpot(TM) Client VM
2561-12-30 18:48:30 FINE: java.vendor = Oracle Corporation
2561-12-30 18:48:30 FINE: java.vm.vendor = Oracle Corporation
2561-12-30 18:48:30 FINE: java.home = C:\Program Files (x86)\Java\jre1.8.0_191
2561-12-30 18:48:30 FINE: java.library.path = C:\Program Files (x86)\Java\jre1.8.0_191\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\IVI Foundation\VISA\WinNT\Bin;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\Program Files (x86)\Yarn\bin\;C:\Program Files\Git\cmd;C:\Users\Asus\AppData\Local\Microsoft\WindowsApps;C:\Users\Asus\AppData\Roaming\npm;C:\Users\Asus\AppData\Local\Yarn\bin;C:\Program Files (x86)\Java\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Users\Asus\AppData\Local\Microsoft\WindowsApps;C:\Users\Asus\AppData\Roaming\npm;C:\Users\Asus\AppData\Local\Yarn\bin;C:\Program Files (x86)\Java\jdk1.8.0_171\bin;;C:\Program Files\Docker Toolbox;.
2561-12-30 18:48:30 FINE: java.class.path = classes;lib\bcprov-jdk15on-159.jar;lib\core-3.3.0.jar;lib\h2-1.4.196.jar;lib\javase-3.3.0.jar;lib\javax.servlet-api-3.1.0.jar;lib\jetty-client-9.3.22.v20171030.jar;lib\jetty-continuation-9.3.22.v20171030.jar;lib\jetty-http-9.3.22.v20171030.jar;lib\jetty-io-9.3.22.v20171030.jar;lib\jetty-proxy-9.3.22.v20171030.jar;lib\jetty-security-9.3.22.v20171030.jar;lib\jetty-server-9.3.22.v20171030.jar;lib\jetty-servlet-9.3.22.v20171030.jar;lib\jetty-servlets-9.3.22.v20171030.jar;lib\jetty-util-9.3.22.v20171030.jar;lib\json-simple-1.1.1.jar;lib\lucene-analyzers-common-5.5.5.jar;lib\lucene-backward-codecs-5.5.5.jar;lib\lucene-core-5.5.5.jar;lib\lucene-queries-5.5.5.jar;lib\lucene-queryparser-5.5.5.jar;lib\slf4j-api-1.7.22.jar;lib\slf4j-jdk14-1.7.22.jar;lib\tika-core-1.13.jar;lib\tika-parsers-1.13.jar;lib\websocket-api-9.3.22.v20171030.jar;lib\websocket-client-9.3.22.v20171030.jar;lib\websocket-common-9.3.22.v20171030.jar;lib\websocket-server-9.3.22.v20171030.jar;lib\websocket-servlet-9.3.22.v20171030.jar;lib\weupnp-0.1.4.jar;conf;addons\classes;addons\lib\*
2561-12-30 18:48:30 FINE: os.arch = x86
2561-12-30 18:48:30 FINE: sun.arch.data.model = 32
2561-12-30 18:48:30 FINE: os.name = Windows 10
2561-12-30 18:48:30 FINE: file.encoding = MS874
2561-12-30 18:48:30 FINE: java.security.policy = null
2561-12-30 18:48:30 FINE: java.security.manager = null
2561-12-30 18:48:30 FINE: nxt.runtime.mode = desktop
2561-12-30 18:48:30 FINE: nxt.runtime.dirProvider = null
2561-12-30 18:48:30 FINE: availableProcessors = 4
2561-12-30 18:48:30 FINE: maxMemory = 259522560
2561-12-30 18:48:30 FINE: processId = 16888
Fatal error: java.lang.NoClassDefFoundError: nxt/db/DbVersion
java.lang.NoClassDefFoundError: nxt/db/DbVersion
        at nxt.Nxt$Init.<clinit>(Nxt.java:357)
        at nxt.Nxt.init(Nxt.java:327)
        at nxt.Nxt.main(Nxt.java:314)
Caused by: java.lang.ClassNotFoundException: nxt.db.DbVersion
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 3 more
2561-12-30 18:48:30 INFO: nxt.launchDesktopApplication = "true"
2561-12-30 18:48:30 INFO: nxt.useStrongSecureRandom = "false"

idk if this really work or it just stuck but I'm gonna run it until it do something
