### ISSUE TITLE
Not Connected Issue

### ISSUE THREAD

**Issue by asimsinan** [sandoche/Proof-of-Stake-Cryptocurrency-generator#21]
I have two nodes running in Amazon. However, I see "not connected" . Is it because I don't have enough nodes or is it related to nxt properties file? 2 is not enough? Genesis accounts and everything is okay. I opened all three ports from amazon. screenhot.
<img width="206" alt="screen shot 2018-10-28 at 15 43 13" src="https://user-images.githubusercontent.com/1812628/47616021-34dccc80-dac8-11e8-8e81-76714916714b.png">
When I try forging I get the following error
2018-10-28 15:56:35 SEVERE: Error in block generation thread
java.lang.NullPointerException
	at nxt.Generator.setLastBlock(Generator.java:323)
	at nxt.Generator.access$400(Generator.java:40)
	at nxt.Generator$1.run(Generator.java:79)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

**Comment by sandoche** [comment]
Have you set in your nxt properties file the ip of the nodes?
Or try to add nodes through the interface.

**Comment by asimsinan** [comment]
Yes I added them to nxt.wellKnownPeers.Did the same thing from interface, it says "already added". However, I managed to forge. Now there is no error. There is another interesting thing. When I copy the whole project to both nodes, they run separately. In one node, I make a transaction, I can see it on that node. However, if I login with the same account in second node, it is not there. It is like they run like separate servers. I opened 7874,7875,7876 inboud outbound ports on aws, waited several hours, still no connection.

**Comment by asimsinan** [comment]
Connection problem solved. It was a port issue. But now not forging :)  throwing the exception in first comment.

**Comment by asimsinan** [comment]
All solved. Forging problem was related to genesisParameters file. It is related to epochBeginning

**Comment by moody210517** [comment]
@asimsinan  I am facing with same forging issue. What should be genesisPublicKey and epochBeginning  in genesisParameters.json file under template/config/data ?
can you explain in details?
