### ISSUE TITLE
Not run script server stop

### ISSUE THREAD

**Issue by torrealba2719** [sandoche/Proof-of-Stake-Cryptocurrency-generator#26]
HELP ME SERVER STOP

Initializing Coinfianza server version 1.11.13
isHeadless=false
Runtime mode nxt.env.CommandLineMode
User home folder /home/elnene/Proof-of-Stake-Cryptocurrency-generator/Coinfianza
Loading nxt-default.properties from classpath
Loading logging-default.properties from classpath
2019-01-18 01:40:21 INFO: nxt.enableStackTraces = "true"
2019-01-18 01:40:21 INFO: nxt.enableLogTraceback = "false"
2019-01-18 01:40:21 INFO: logging enabled
2019-01-18 01:40:21 INFO: socksProxyHost not defined
2019-01-18 01:40:21 INFO: socksProxyPort not defined
2019-01-18 01:40:21 FINE: java.version = 1.8.0_201
2019-01-18 01:40:21 FINE: java.vm.version = 25.201-b09
2019-01-18 01:40:21 FINE: java.vm.name = Java HotSpot(TM) Server VM
2019-01-18 01:40:21 FINE: java.vendor = Oracle Corporation
2019-01-18 01:40:21 FINE: java.vm.vendor = Oracle Corporation
2019-01-18 01:40:21 FINE: java.home = /usr/lib/jvm/java-8-oracle/jre
2019-01-18 01:40:21 FINE: java.library.path = /usr/java/packages/lib/i386:/lib:/usr/lib
2019-01-18 01:40:21 FINE: java.class.path = classes:lib/tika-core-1.13.jar:lib/jetty-continuation-9.3.22.v20171030.jar:lib/jetty-proxy-9.3.22.v20171030.jar:lib/slf4j-jdk14-1.7.22.jar:lib/lucene-core-5.5.5.jar:lib/websocket-client-9.3.22.v20171030.jar:lib/javax.servlet-api-3.1.0.jar:lib/bcprov-jdk15on-159.jar:lib/jetty-server-9.3.22.v20171030.jar:lib/h2-1.4.196.jar:lib/websocket-common-9.3.22.v20171030.jar:lib/lucene-analyzers-common-5.5.5.jar:lib/jetty-client-9.3.22.v20171030.jar:lib/jetty-http-9.3.22.v20171030.jar:lib/weupnp-0.1.4.jar:lib/jetty-servlet-9.3.22.v20171030.jar:lib/websocket-servlet-9.3.22.v20171030.jar:lib/lucene-queries-5.5.5.jar:lib/lucene-backward-codecs-5.5.5.jar:lib/core-3.3.0.jar:lib/slf4j-api-1.7.22.jar:lib/jetty-io-9.3.22.v20171030.jar:lib/jetty-security-9.3.22.v20171030.jar:lib/jetty-servlets-9.3.22.v20171030.jar:lib/json-simple-1.1.1.jar:lib/websocket-api-9.3.22.v20171030.jar:lib/tika-parsers-1.13.jar:lib/lucene-queryparser-5.5.5.jar:lib/javase-3.3.0.jar:lib/websocket-server-9.3.22.v20171030.jar:lib/jetty-util-9.3.22.v20171030.jar:conf:addons/classes:addons/lib/*
2019-01-18 01:40:21 FINE: os.arch = i386
2019-01-18 01:40:21 FINE: sun.arch.data.model = 32
2019-01-18 01:40:21 FINE: os.name = Linux
2019-01-18 01:40:21 FINE: file.encoding = UTF-8
2019-01-18 01:40:21 FINE: java.security.policy = null
2019-01-18 01:40:21 FINE: java.security.manager = null
2019-01-18 01:40:21 FINE: nxt.runtime.mode = null
2019-01-18 01:40:21 FINE: nxt.runtime.dirProvider = null
2019-01-18 01:40:21 FINE: availableProcessors = 2
2019-01-18 01:40:21 FINE: maxMemory = 934019072
2019-01-18 01:40:21 FINE: processId = 551
2019-01-18 01:40:21 INFO: nxt.isTestnet = "false"
2019-01-18 01:40:21 INFO: nxt.isOffline = "false"
2019-01-18 01:40:21 INFO: nxt.isLightClient = "false"
2019-01-18 01:40:21 INFO: nxt.customLoginWarning not defined
2019-01-18 01:40:21 INFO: nxt.maxNumberOfTransactions not defined or not numeric, using default value 255
2019-01-18 01:40:21 INFO: nxt.maxRollback = "800"
2019-01-18 01:40:21 INFO: nxt.forgingDelay = "20"
2019-01-18 01:40:21 INFO: nxt.forgingSpeedup = "3"
2019-01-18 01:40:21 INFO: nxt.batchCommitSize = "100"
2019-01-18 01:40:21 INFO: nxt.maxPrunableLifetime = "7776000"
2019-01-18 01:40:21 INFO: nxt.includeExpiredPrunable = "true"
2019-01-18 01:40:21 INFO: nxt.correctInvalidFees = "false"
2019-01-18 01:40:21 INFO: nxt.statementLogThreshold = "10000"
2019-01-18 01:40:21 INFO: nxt.transactionLogThreshold = "15000"
2019-01-18 01:40:21 INFO: nxt.transactionLogInterval = "15"
2019-01-18 01:40:21 INFO: nxt.dbCacheKB = "0"
2019-01-18 01:40:21 INFO: nxt.dbUrl not defined
2019-01-18 01:40:21 INFO: nxt.dbType = "h2"
2019-01-18 01:40:21 INFO: nxt.dbDir = "./nxt_db/nxt"
2019-01-18 01:40:21 INFO: nxt.dbParams = "DB_CLOSE_ON_EXIT=FALSE;MVCC=TRUE;MV_STORE=FALSE"
2019-01-18 01:40:21 INFO: nxt.dbUsername = "sa"
2019-01-18 01:40:21 INFO: nxt.dbPassword = "{not logged}"
2019-01-18 01:40:21 INFO: nxt.maxDbConnections = "30"
2019-01-18 01:40:21 INFO: nxt.dbLoginTimeout = "70"
2019-01-18 01:40:21 INFO: nxt.dbDefaultLockTimeout = "60"
2019-01-18 01:40:21 INFO: nxt.dbMaxMemoryRows = "1000000"
2019-01-18 01:40:21 FINE: Database jdbc url set to jdbc:h2:./nxt_db/nxt;DB_CLOSE_ON_EXIT=FALSE;MVCC=TRUE;MV_STORE=FALSE;CACHE_SIZE=262144 username sa
2019-01-18 01:40:21 INFO: nxt.useStrongSecureRandom = "false"
2019-01-18 01:40:24 FINE: Database connection pool current size: 1
2019-01-18 01:40:24 INFO: Database update may take a while if needed, current db version 237...
2019-01-18 01:40:24 INFO: nxt.enableTransactionRebroadcasting = "true"
2019-01-18 01:40:24 INFO: nxt.testUnconfirmedTransactions not defined, using default false
2019-01-18 01:40:24 INFO: nxt.maxUnconfirmedTransactions = "2000"
2019-01-18 01:40:24 INFO: nxt.trimDerivedTables = "true"
2019-01-18 01:40:24 INFO: nxt.numberOfForkConfirmations = "2"
2019-01-18 01:40:24 INFO: nxt.simulateEndlessDownload not defined, using default false
2019-01-18 01:40:24 INFO: nxt.trimFrequency = "1000"
2019-01-18 01:40:24 INFO: nxt.disableGetMoreBlocksThread not defined, using default false
2019-01-18 01:40:24 INFO: nxt.disableProcessTransactionsThread not defined, using default false
2019-01-18 01:40:24 INFO: nxt.disableRebroadcastTransactionsThread not defined, using default false
2019-01-18 01:40:24 INFO: nxt.disableRemoveUnconfirmedTransactionsThread not defined, using default false
2019-01-18 01:40:24 INFO: nxt.disableProcessWaitingTransactionsThread not defined, using default false
2019-01-18 01:40:24 INFO: nxt.enablePublicKeyCache = "true"
2019-01-18 01:40:24 INFO: nxt.ledgerTrimKeep = "30000"
2019-01-18 01:40:24 INFO: nxt.ledgerAccounts = "*"
2019-01-18 01:40:24 INFO: Account ledger is tracking all accounts
2019-01-18 01:40:24 INFO: nxt.ledgerLogUnconfirmed = "2"
2019-01-18 01:40:24 INFO: nxt.processPolls = "true"
2019-01-18 01:40:24 INFO: nxt.deleteFinishedShufflings = "false"
2019-01-18 01:40:24 INFO: nxt.maxPeerRequestSize not defined or not numeric, using default value 1048576
2019-01-18 01:40:24 INFO: nxt.maxPeerResponseSize not defined or not numeric, using default value 1048576
2019-01-18 01:40:24 INFO: nxt.maxPeerMessageSize not defined or not numeric, using default value 10485760
2019-01-18 01:40:24 INFO: nxt.hideErrorDetails = "false"
2019-01-18 01:40:24 INFO: nxt.myPlatform not defined
2019-01-18 01:40:24 INFO: nxt.myAddress not defined
2019-01-18 01:40:24 INFO: nxt.peerServerPort = "7874"
2019-01-18 01:40:24 INFO: nxt.shareMyAddress = "true"
2019-01-18 01:40:24 INFO: nxt.enablePeerUPnP = "true"
2019-01-18 01:40:24 INFO: nxt.myHallmark not defined
2019-01-18 01:40:24 INFO: nxt.adminPassword not defined
2019-01-18 01:40:24 INFO: nxt.maxAPIRecords = "100"
2019-01-18 01:40:24 INFO: nxt.enableAPIUPnP = "false"
2019-01-18 01:40:24 INFO: nxt.apiServerIdleTimeout = "30000"
2019-01-18 01:40:24 INFO: nxt.apiServerCORS = "true"
2019-01-18 01:40:24 INFO: nxt.forwardedForHeader not defined
2019-01-18 01:40:24 INFO: nxt.disabledAPIs not defined
2019-01-18 01:40:24 INFO: nxt.disabledAPITags not defined
2019-01-18 01:40:24 INFO: nxt.allowedBotHosts = "127.0.0.1; localhost; [0:0:0:0:0:0:0:1];"
2019-01-18 01:40:24 INFO: nxt.enableAPIServer = "true"
2019-01-18 01:40:24 INFO: nxt.apiServerPort = "7876"
2019-01-18 01:40:24 INFO: nxt.apiServerSSLPort = "7876"
2019-01-18 01:40:24 INFO: nxt.apiServerHost = "127.0.0.1"
2019-01-18 01:40:24 INFO: nxt.disableAdminPassword = "false"
2019-01-18 01:40:24 INFO: nxt.apiSSL = "false"
2019-01-18 01:40:24 INFO: API server using HTTP port 7876
2019-01-18 01:40:24 INFO: nxt.apiResourceBase = "./html/www"
2019-01-18 01:40:24 INFO: nxt.apiWelcomeFile = "index.html"
2019-01-18 01:40:24 INFO: nxt.javadocResourceBase = "./html/doc"
2019-01-18 01:40:24 INFO: nxt.maxUploadFileSize not defined or not numeric, using default value 0
2019-01-18 01:40:24 INFO: nxt.maxUploadFileSize not defined or not numeric, using default value 0
2019-01-18 01:40:24 INFO: nxt.enableAPIServerGZIPFilter not defined, using default false
2019-01-18 01:40:24 INFO: nxt.apiFrameOptionsSameOrigin = "true"
2019-01-18 01:40:24 FINE: My peer info:
{"application":"Coinfianza","services":"0","version":"1.11.13","platform":"Linux i386","shareAddress":true}
2019-01-18 01:40:24 INFO: nxt.defaultPeers not defined
2019-01-18 01:40:24 INFO: nxt.wellKnownPeers not defined
2019-01-18 01:40:24 INFO: nxt.knownBlacklistedPeers not defined
2019-01-18 01:40:24 INFO: nxt.maxNumberOfInboundConnections = "2000"
2019-01-18 01:40:24 INFO: nxt.maxNumberOfOutboundConnections = "50"
2019-01-18 01:40:24 INFO: nxt.maxNumberOfConnectedPublicPeers = "20"
2019-01-18 01:40:24 INFO: nxt.maxNumberOfKnownPeers = "2000"
2019-01-18 01:40:24 INFO: nxt.minNumberOfKnownPeers = "1000"
2019-01-18 01:40:24 INFO: nxt.connectTimeout = "10000"
2019-01-18 01:40:24 INFO: nxt.readTimeout = "20000"
2019-01-18 01:40:24 INFO: nxt.enableHallmarkProtection = "true"
2019-01-18 01:40:24 INFO: nxt.pushThreshold = "0"
2019-01-18 01:40:24 INFO: nxt.pullThreshold = "0"
2019-01-18 01:40:24 INFO: nxt.useWebSockets = "true"
2019-01-18 01:40:24 INFO: nxt.webSocketIdleTimeout = "900000"
2019-01-18 01:40:24 INFO: nxt.enablePeerServerGZIPFilter = "true"
2019-01-18 01:40:24 INFO: nxt.blacklistingPeriod = "600000"
2019-01-18 01:40:24 INFO: nxt.communicationLoggingMask = "0"
2019-01-18 01:40:24 INFO: nxt.sendToPeersLimit = "10"
2019-01-18 01:40:25 INFO: nxt.usePeersDb = "true"
2019-01-18 01:40:25 INFO: nxt.savePeers = "true"
2019-01-18 01:40:25 INFO: nxt.getMorePeers = "true"
2019-01-18 01:40:25 INFO: nxt.cjdnsOnly = "false"
2019-01-18 01:40:25 INFO: nxt.ignorePeerAnnouncedAddress = "false"
2019-01-18 01:40:25 INFO: nxt.disablePeerConnectingThread not defined, using default false
2019-01-18 01:40:25 INFO: nxt.disablePeerUnBlacklistingThread not defined, using default false
2019-01-18 01:40:25 INFO: nxt.disableGetMorePeersThread not defined, using default false
2019-01-18 01:40:25 INFO: nxt.peerServerHost = "0.0.0.0"
2019-01-18 01:40:25 INFO: nxt.peerServerIdleTimeout = "30000"
2019-01-18 01:40:25 INFO: nxt.enablePeerServerDoSFilter = "true"
2019-01-18 01:40:25 INFO: nxt.peerServerDoSFilter.maxRequestsPerSec = "30"
2019-01-18 01:40:25 INFO: nxt.peerServerDoSFilter.delayMs = "1000"
2019-01-18 01:40:25 INFO: nxt.peerServerDoSFilter.maxRequestMs = "300000"
2019-01-18 01:40:25 INFO: nxt.enableAPIProxy = "true"
2019-01-18 01:40:25 INFO: nxt.apiProxyBlacklistingPeriod = "1800000"
2019-01-18 01:40:25 INFO: nxt.forceAPIProxyServerURL not defined
2019-01-18 01:40:25 INFO: nxt.disableAPIProxyPeersUpdateThread not defined, using default false
2019-01-18 01:40:25 INFO: nxt.maxNumberOfForgers = "100"
2019-01-18 01:40:25 INFO: nxt.enableFakeForging not defined, using default false
2019-01-18 01:40:25 INFO: nxt.disableGenerateBlocksThread not defined, using default false
2019-01-18 01:40:25 INFO: nxt.addOns not defined
2019-01-18 01:40:25 INFO: nxt.debugTraceQuote = """
2019-01-18 01:40:25 INFO: nxt.debugTraceSeparator = "	"
2019-01-18 01:40:25 INFO: nxt.debugLogUnconfirmed = "false"
2019-01-18 01:40:25 INFO: nxt.debugTraceAccounts not defined
2019-01-18 01:40:25 INFO: nxt.debugTraceLog = "nxt-trace.csv"
2019-01-18 01:40:25 FINE: Running 2 tasks...
2019-01-18 01:40:25 INFO: Genesis block not in database, starting from scratch
2019-01-18 01:40:25 FINE: Loading known peers from the database...
2019-01-18 01:40:25 FINE: Database connection pool current size: 2
2019-01-18 01:40:25 FINE: Average database transaction time is 0,018 seconds
Exception in thread "Thread-3" java.lang.NullPointerException
	at java.security.DigestInputStream.read(DigestInputStream.java:161)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at org.json.simple.parser.Yylex.zzRefill(Yylex.java:345)
	at org.json.simple.parser.Yylex.yylex(Yylex.java:541)
	at org.json.simple.parser.JSONParser.nextToken(JSONParser.java:269)
	at org.json.simple.parser.JSONParser.parse(JSONParser.java:118)
	at org.json.simple.parser.JSONParser.parse(JSONParser.java:92)
	at org.json.simple.JSONValue.parseWithException(JSONValue.java:73)
	at nxt.Genesis.loadGenesisAccountsJSON(Genesis.java:59)
	at nxt.Genesis.newGenesisBlock(Genesis.java:69)
	at nxt.BlockchainProcessorImpl.addGenesisBlock(BlockchainProcessorImpl.java:1272)
	at nxt.BlockchainProcessorImpl.lambda$new$5(BlockchainProcessorImpl.java:971)
	at nxt.util.ThreadPool.lambda$runAll$1(ThreadPool.java:126)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.lang.NullPointerException
		at java.io.FilterInputStream.close(FilterInputStream.java:181)
		at sun.nio.cs.StreamDecoder.implClose(StreamDecoder.java:378)
		at sun.nio.cs.StreamDecoder.close(StreamDecoder.java:193)
		at java.io.InputStreamReader.close(InputStreamReader.java:199)
		at nxt.Genesis.loadGenesisAccountsJSON(Genesis.java:60)
		... 5 more
2019-01-18 01:40:25 SEVERE: Errors running startup tasks:
null

java.lang.RuntimeException: Errors running startup tasks:
null

	at nxt.util.ThreadPool.runAll(ThreadPool.java:144)
	at nxt.util.ThreadPool.start(ThreadPool.java:74)
	at nxt.Nxt$Init.<clinit>(Nxt.java:395)
	at nxt.Nxt.init(Nxt.java:327)
	at nxt.Nxt.main(Nxt.java:314)
2019-01-18 01:40:25 INFO: Shutting down...
2019-01-18 01:40:25 INFO: nxt.maxNumberOfMonitors = "100"
2019-01-18 01:40:25 INFO: shutting down networkService
2019-01-18 01:40:25 INFO: shutting down sendingService
2019-01-18 01:40:25 INFO: shutting down peersService
2019-01-18 01:40:25 INFO: Database shutdown completed
2019-01-18 01:40:25 INFO: Coinfianza server 1.11.13 stopped.

**Comment by sandoche** [comment]
Try deleting `nxt_db` folder and start again.
