### ISSUE TITLE
error building installer

### ISSUE THREAD

**Issue by mathiasvanheule** [sandoche/Proof-of-Stake-Cryptocurrency-generator#30]
When building the installer using ./win-release-package.sh in a cygwin shell I get the following output:
java.io.FileNotFoundException: resource\nxt.manifest.mf (Access is denied)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at sun.tools.jar.Main.run(Main.java:175)
        at sun.tools.jar.Main.main(Main.java:1288)

build-exe.log actually logs 0 errors.

build-installer.log logs the following:

Fatal error :
   Source file nxt.jar (F:\...\...\.\nxt.jar) not found
com.izforge.izpack.api.exception.CompilerException: Source file nxt.jar (F:\...\...\.\nxt.jar) not found
	at com.izforge.izpack.compiler.CompilerConfig.processFileChildren(CompilerConfig.java:1163)
	at com.izforge.izpack.compiler.CompilerConfig.addPacksSingle(CompilerConfig.java:828)
	at com.izforge.izpack.compiler.CompilerConfig.addPacks(CompilerConfig.java:724)
	at com.izforge.izpack.compiler.CompilerConfig.executeCompiler(CompilerConfig.java:342)
	at com.izforge.izpack.compiler.bootstrap.CompilerLauncher.main(CompilerLauncher.java:52)
Caused by: java.io.FileNotFoundException: Source file nxt.jar (F:\...\...\.\nxt.jar) not found
	at com.izforge.izpack.compiler.CompilerConfig.processFileChildren(CompilerConfig.java:1096)
	... 4 more

Any idea whats causing this?

**Comment by mathiasvanheule** [comment]
Managed to build the installer now

**Comment by adi6409** [comment]
How did you build it eventually? i am facing the same problem
