### ISSUE TITLE
Error on outbound connections after finished blockchain download, nxt wallet dashboard did not show sign of downloading 

### ISSUE THREAD

**Issue by kate1823** [sandoche/Proof-of-Stake-Cryptocurrency-generator#31]
2019-08-01 21:20:08 INFO: Blockchain download in progress
2019-08-01 21:20:09 FINE: Got 2 confirmations
2019-08-01 21:20:09 INFO: Downloaded 16 blocks in 1 s, 12 per s, 0 min left
2019-08-01 21:20:09 INFO: Finished blockchain download
2019-08-01 21:20:37 FINE: Peer 80.211.145.9 version null returned error: {"error":"Maximum number of inbound connections exceeded"}, request was: {"protocol":1,"application":"NRS","requestType":"getInfo","blockchainState":0,"services":"0","version":"1.11.13","platform":"Mac OS X x86_64","shareAddress":true}, disconnecting
2019-08-01 21:24:01 FINE: Database connection pool current size: 3
2019-08-01 21:24:01 FINE: Database connection pool current size: 4
2019-08-01 21:24:01 FINE: Database connection pool current size: 5
2019-08-01 21:24:01 FINE: Database connection pool current size: 6
2019-08-01 21:29:38 FINE: Too many outbound connections, deactivating peer 159.65.126.29
2019-08-01 21:29:38 FINE: Too many outbound connections, deactivating peer 142.44.212.178
2019-08-01 21:30:08 FINE: Too many outbound connections, deactivating peer 162.243.194.123
2019-08-01 21:30:08 FINE: Too many outbound connections, deactivating peer 85.94.178.144
2019-08-01 21:30:37 FINE: Connect: peer 217.26.24.27 has new announced address ncnode.prao.ru, old is 217.26.24.27
2019-08-01 21:30:37 FINE: Removing old announced address 217.26.24.27 for peer 217.26.24.27
2019-08-01 21:31:08 FINE: Too many outbound connections, deactivating peer 185.137.234.120
2019-08-01 21:31:08 FINE: Peer 80.211.145.9 version null returned error: {"error":"Maximum number of inbound connections exceeded"}, request was: {"protocol":1,"application":"NRS","requestType":"getInfo","blockchainState":0,"services":"0","version":"1.11.13","platform":"Mac OS X x86_64","shareAddress":true}, disconnecting
2019-08-01 21:31:09 FINE: Too many outbound connections, deactivating peer 89.254.211.94
2019-08-01 21:31:29 FINE: Too many outbound connections, deactivating peer 89.212.19.49
2019-08-01 21:31:30 FINE: Too many outbound connections, deactivating peer 84.40.73.180
2019-08-01 21:31:59 FINE: Too many outbound connections, deactivating peer 217.182.93.187
2019-08-01 21:32:32 FINE: Too many outbound connections, deactivating peer 83.162.253.185
2019-08-01 21:33:00 FINE: Too many outbound connections, deactivating peer 103.77.48.21

**Comment by kate1823** [comment]
Realised that it was the version problem, tried to upgrade from 13 to 15, the downloading sign is shown on the wallet but new error is: appear No openAPI peers found. Please wait or try to add an openAPI peer manually.No openAPI peers found. Please wait or try to add an openAPI peer manually.

2019-08-01 21:55:46 SEVERE: Failed to start API server
java.net.BindException: Address already in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:455)
	at java.base/sun.nio.ch.Net.bind(Net.java:447)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:219)
	at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:80)
	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:351)
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:319)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:235)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.server.Server.doStart(Server.java:401)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at nxt.http.API.lambda$static$1(API.java:293)
	at nxt.util.ThreadPool.lambda$runAll$1(ThreadPool.java:126)
	at java.base/java.lang.Thread.run(Thread.java:835)
Exception in thread "Thread-4" java.lang.RuntimeException: java.net.BindException: Address already in use
	at nxt.http.API.lambda$static$1(API.java:301)
	at nxt.util.ThreadPool.lambda$runAll$1(ThreadPool.java:126)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.net.BindException: Address already in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:455)
	at java.base/sun.nio.ch.Net.bind(Net.java:447)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:219)
	at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:80)
	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:351)
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:319)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:235)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.server.Server.doStart(Server.java:401)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at nxt.http.API.lambda$static$1(API.java:293)
	... 2 more
2019-08-01 21:55:46 FINE: UPnP gateway device found on 192.168.0.58
2019-08-01 21:55:46 FINE: Using UPnP gateway device on 192.168.0.58
2019-08-01 21:55:46 INFO: External IP address is 192.168.1.2
2019-08-01 21:55:46 FINE: Mapped port [192.168.1.2]:7874
2019-08-01 21:55:46 SEVERE: Failed to start peer networking server
java.net.BindException: Address already in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:455)
	at java.base/sun.nio.ch.Net.bind(Net.java:447)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:219)
	at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:80)
	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:351)
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:319)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:235)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.server.Server.doStart(Server.java:401)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at nxt.peer.Peers$Init.lambda$static$0(Peers.java:459)
	at nxt.util.ThreadPool.lambda$runAll$1(ThreadPool.java:126)
	at java.base/java.lang.Thread.run(Thread.java:835)
Exception in thread "Thread-5" java.lang.RuntimeException: java.net.BindException: Address already in use
	at nxt.peer.Peers$Init.lambda$static$0(Peers.java:463)
	at nxt.util.ThreadPool.lambda$runAll$1(ThreadPool.java:126)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.net.BindException: Address already in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:455)
	at java.base/sun.nio.ch.Net.bind(Net.java:447)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:219)
	at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:80)
	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:351)
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:319)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:235)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.server.Server.doStart(Server.java:401)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at nxt.peer.Peers$Init.lambda$static$0(Peers.java:459)
	... 2 more
2019-08-01 21:55:46 SEVERE: Errors running startup tasks:
java.net.BindException: Address already in use
java.net.BindException: Address already in use

java.lang.RuntimeException: Errors running startup tasks:
java.net.BindException: Address already in use
java.net.BindException: Address already in use

	at nxt.util.ThreadPool.runAll(ThreadPool.java:144)
	at nxt.util.ThreadPool.start(ThreadPool.java:78)
	at nxt.Nxt$Init.<clinit>(Nxt.java:400)
	at nxt.Nxt.init(Nxt.java:328)
	at nxt.Nxt.main(Nxt.java:315)
2019-08-01 21:55:46 INFO: Shutting down...
2019-08-01 21:55:46 INFO: Shutting down nxt.addons.JPLSnapshot
2019-08-01 21:55:46 INFO: nxt.maxNumberOfMonitors = "100"
2019-08-01 21:55:46 INFO: shutting down networkService
2019-08-01 21:55:46 FINE: Mapping deleted for port 7874
2019-08-01 21:55:46 INFO: shutting down sendingService
2019-08-01 21:55:46 INFO: shutting down peersService
2019-08-01 21:55:46 INFO: Database shutdown completed
2019-08-01 21:55:46 INFO: Nxt server 1.11.13 stopped.
