### ISSUE TITLE
run.sh Genesis Block

### ISSUE THREAD

**Issue by Oxichain** [sandoche/Proof-of-Stake-Cryptocurrency-generator#59]
Hello,
I just completed the sh ./compile.sh command and then ran sh ./run.sh. Now, this error comes up:

2021-04-30 08:41:40 INFO: Genesis block not in database, starting from scratch
Exception in thread "Thread-4" java.lang.ExceptionInInitializerError
	at nxt.util.Convert.toEpochTime(Convert.java:135)
	at nxt.util.Time$EpochTime.getTime(Time.java:28)
	at nxt.Nxt.getEpochTime(Nxt.java:304)
	at nxt.peer.Peers$1.run(Peers.java:356)
	at nxt.util.ThreadPool.lambda$runAll$1(ThreadPool.java:126)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Failed to load genesis parameters
	at nxt.Genesis.<clinit>(Genesis.java:49)
	... 6 more
Caused by: java.text.ParseException: Unparseable date: "2021-04-29"
	at java.text.DateFormat.parse(DateFormat.java:366)
	at nxt.Genesis.<clinit>(Genesis.java:47)
	... 6 more
2021-04-30 08:41:40 FINE: Average database transaction time is 0.004 seconds
Exception in thread "Thread-3" java.lang.NoClassDefFoundError: Could not initialize class nxt.Genesis
	at nxt.BlockchainProcessorImpl.addGenesisBlock(BlockchainProcessorImpl.java:1272)
	at nxt.BlockchainProcessorImpl.lambda$new$5(BlockchainProcessorImpl.java:971)
	at nxt.util.ThreadPool.lambda$runAll$1(ThreadPool.java:126)
	at java.lang.Thread.run(Thread.java:748)
2021-04-30 08:41:40 SEVERE: Errors running startup tasks:
null
Could not initialize class nxt.Genesis

java.lang.RuntimeException: Errors running startup tasks:
null
Could not initialize class nxt.Genesis

	at nxt.util.ThreadPool.runAll(ThreadPool.java:144)
	at nxt.util.ThreadPool.start(ThreadPool.java:74)
	at nxt.Nxt$Init.<clinit>(Nxt.java:395)
	at nxt.Nxt.init(Nxt.java:327)
	at nxt.Nxt.main(Nxt.java:314)
2021-04-30 08:41:40 INFO: Shutting down...
2021-04-30 08:41:40 INFO: nxt.maxNumberOfMonitors = "100"
2021-04-30 08:41:40 INFO: shutting down networkService
2021-04-30 08:41:40 INFO: shutting down sendingService
2021-04-30 08:41:40 INFO: shutting down peersService
2021-04-30 08:41:40 INFO: Database shutdown completed
2021-04-30 08:41:40 INFO: OxiChain server 1.11.15 stopped.

**Comment by moody210517** [comment]
I think you did not update the genesisParameters.json file  under templates/confi/data
Please add right public key and try again.

**Comment by Oxichain** [comment]
Alright,  thank you. I will try. But what shall I put into balance?

**Comment by moody210517** [comment]
{
    "balances": {
         "my nxt address here": 90000000000000000
     },
     "publicKeys": [
         "the public key of this nxt address"
     ]
 }

**Comment by Oxichain** [comment]
I did that now but it still gives me the same error.
